### PR TITLE
week-1

### PR DESCRIPTION
**Pull request by tom54699**
名字: 廖梓兆
簡單報告:
1. 老師，你那個app.py我沒有動，但我另外用了一個run.py，想練習看看blueprint。
2. 因為上週和師睿同學都在研究Docker，所以我們也試看看用Docker部屬。

以下是三個API的url
http://35.79.132.71:3000/api/attractions?page=0
http://35.79.132.71:3000/api/attractions?page=0&keyword=養身溫泉

http://35.79.132.71:3000/api/attraction/2
http://35.79.132.71:3000/api/attraction/呵呵

http://35.79.132.71:3000/api/categories

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Re-request review after you solve issues below:

1. Response format of http://35.79.132.71:3000/api/attraction/2 is incorrect.

2. nextPage field should be null if there is no more pages. I mean nextPage field of http://35.79.132.71:3000/api/attractions?page=4 should be null.

3. We should use keyword to filter all attractions and paginate them. If there are 14 attractions after filtering, we get only 2 pages. If there are 4 attractions after filtering, we get only 1 page containing all of these 4 attractions.

**Comment by tom54699** [comment]
晚上好，老師
1. 已修正，加上data
http://35.79.132.71:3000/api/attraction/2
2. 已修正，未找到資料會顯示為null
http://35.79.132.71:3000/api/attractions?page=5
3. 已修正，大改並使用paginate()來控制頁數 
http://35.79.132.71:3000/api/attractions?page=0&keyword=養生溫泉

作業需求網址:
http://35.79.132.71:3000/api/attractions?page=1
http://35.79.132.71:3000/api/attractions?page=0&keyword=藝文館所
http://35.79.132.71:3000/api/attractions?page=0&keyword=北
http://35.79.132.71:3000/api/attraction/10

**Review by cwpeng — CHANGES_REQUESTED** [review]
1 and 3 are OK. But not 2.

- `nextPage` field should be null if there is no more pages. I mean `nextPage` field of http://35.79.132.71:3000/api/attractions?page=4 should be null.

Keep `data` field empty is OK.

**Comment by tom54699** [comment]
已修改，增加頁數判斷式
`        if page >= pages.pages:
            page_data["nextPage"] = "null"`

http://35.79.132.71:3000/api/attractions?page=4
http://35.79.132.71:3000/api/attractions?page=1&keyword=藝文館所

**Review by cwpeng — CHANGES_REQUESTED** [review]
`null` is not `"null"`

**Comment by tom54699** [comment]
已修改
1. Python None is null.
`            if page >= query_list.pages:
                selected_page_data["nextPage"] = None`
2. Keep data field empty
http://35.79.132.71:3000/api/attractions?page=4
http://35.79.132.71:3000/api/attractions?page=1&keyword=藝文館所

**Review by cwpeng — APPROVED** [review]
Good. You are the First One.

**Pull request merged**
