### PR TITLE
Week-5

### PR DESCRIPTION
**Pull request by tom54699**
名字: 廖梓兆

網址:  http://taipeitrip.serveirc.com

謝謝老師

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Don't redirect to /booking, just show dialog when we click 預定行程 without signing in.

**Comment by tom54699** [comment]
已完成修改

網址: http://taipeitrip.serveirc.com

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by tom54699** [comment]
謝謝老師!! :)

**Pull request merged**
